// packages/sdk/demos/web/spa/svelte/ts/src/lib/components/ui/dialog-title.svelte
<script lang="ts">
  import { Dialog as DialogPrimitive } from "bits-ui";
  import { cn } from "$lib/utils";
  import type { Snippet } from "svelte";

  interface Props {
    class?: string;
    children?: Snippet;
  }

  let { class: className, children }: Props = $props();
</script>

<DialogPrimitive.Title
  class={cn("text-lg font-semibold leading-none tracking-tight", className)}
>
  {@render children?.()}
</DialogPrimitive.Title>

// packages/sdk/demos/web/spa/vue/ts/src/components/ui/DialogTitle.vue
<script setup lang="ts">
import { DialogTitle } from 'reka-ui';
import { cn } from '@/lib/utils';

interface Props {
  class?: string;
}

const props = defineProps<Props>();
</script>

<template>
  <DialogTitle :class="cn('text-lg font-semibold leading-none tracking-tight', props.class)">
    <slot />
  </DialogTitle>
</template>
