// packages/sdk/demos/web/spa/svelte/ts/src/lib/components/ui/dialog-description.svelte
<script lang="ts">
  import { Dialog as DialogPrimitive } from "bits-ui";
  import { cn } from "$lib/utils";
  import type { Snippet } from "svelte";

  interface Props {
    class?: string;
    children?: Snippet;
  }

  let { class: className, children }: Props = $props();
</script>

<DialogPrimitive.Description class={cn("text-sm text-muted-foreground", className)}>
  {@render children?.()}
</DialogPrimitive.Description>

// packages/sdk/demos/web/spa/vue/ts/src/components/ui/DialogDescription.vue
<script setup lang="ts">
import { DialogDescription } from 'reka-ui';
import { cn } from '@/lib/utils';

interface Props {
  class?: string;
}

const props = defineProps<Props>();
</script>

<template>
  <DialogDescription :class="cn('text-sm text-muted-foreground', props.class)">
    <slot />
  </DialogDescription>
</template>
