// packages/sdk/demos/web/spa/svelte/ts/src/lib/components/ui/label.svelte
<script lang="ts">
  import { cn } from "$lib/utils";
  import type { HTMLLabelAttributes } from "svelte/elements";

  interface Props extends HTMLLabelAttributes {}

  let { class: className, children, ...restProps }: Props = $props();
</script>

<label
  class={cn(
    "text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70",
    className
  )}
  {...restProps}
>
  {@render children?.()}
</label>

// packages/sdk/demos/web/spa/vue/ts/src/components/ui/Label.vue
<script setup lang="ts">
import { cn } from '@/lib/utils';

interface Props {
  class?: string;
  for?: string;
}

const props = defineProps<Props>();
</script>

<template>
  <label
    :class="
      cn(
        'text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
        props.class
      )
    "
    :for="props.for"
  >
    <slot />
  </label>
</template>
