// packages/sdk/demos/web/spa/svelte/ts/src/lib/components/ui/table-cell.svelte
<script lang="ts">
  import { cn } from "$lib/utils";
  import type { HTMLTdAttributes } from "svelte/elements";

  interface Props extends HTMLTdAttributes {}

  let { class: className, children, ...restProps }: Props = $props();
</script>

<td
  class={cn(
    "p-2 align-middle [&:has([role=checkbox])]:pr-0 [&>[role=checkbox]]:translate-y-[2px]",
    className
  )}
  {...restProps}
>
  {@render children?.()}
</td>

// packages/sdk/demos/web/spa/vue/ts/src/components/ui/TableCell.vue
<script setup lang="ts">
import { cn } from '@/lib/utils';

interface Props {
  class?: string;
  colspan?: number;
}

const props = defineProps<Props>();
</script>

<template>
  <td
    :class="
      cn(
        'p-2 align-middle [&:has([role=checkbox])]:pr-0 *:[[role=checkbox]]:translate-y-[2px]',
        props.class
      )
    "
    :colspan="colspan"
  >
    <slot />
  </td>
</template>
