// packages/sdk/demos/web/spa/vue/ts/src/App.vue
<script setup lang="ts">
import { Toaster } from 'vue-sonner';
import Header from '@/components/Header.vue';
</script>

<template>
  <div class="min-h-screen bg-background">
    <Header />
    <main class="container mx-auto px-4 py-6">
      <router-view />
    </main>
    <Toaster />
  </div>
</template>

// packages/table-adapter-react/demos/spa/ts/src/App.tsx
import { Routes, Route } from "react-router";
import { Header } from "@/components/Header";
import { ProtectedRoute } from "@/components/ProtectedRoute";
import { Home } from "@/pages/Home";
import { Callback } from "@/pages/Callback";
import { CustomerTable } from "@/pages/CustomerTable";

function App(): React.ReactElement {
  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="container mx-auto px-4 py-6">
        <Routes>
          {/* Public routes */}
          <Route path="/" element={<Home />} />
          <Route path="/callback" element={<Callback />} />

          {/* Protected routes */}
          <Route element={<ProtectedRoute />}>
            <Route path="/customers" element={<CustomerTable />} />
          </Route>
        </Routes>
      </main>
    </div>
  );
}

export default App;
