// packages/sdk/demos/web/spa/svelte/ts/src/lib/components/ui/skeleton.svelte
<script lang="ts">
  import { cn } from "$lib/utils";
  import type { HTMLAttributes } from "svelte/elements";

  interface Props extends HTMLAttributes<HTMLDivElement> {}

  let { class: className, ...restProps }: Props = $props();
</script>

<div
  class={cn("animate-pulse rounded-md bg-primary/10", className)}
  {...restProps}
></div>

// packages/table-adapter-react/demos/spa/ts/src/components/ui/skeleton.tsx
import * as React from "react";
import { cn } from "@/lib/utils";

function Skeleton({
  className,
  ...props
}: React.ComponentProps<"div">): React.ReactElement {
  return (
    <div
      data-slot="skeleton"
      className={cn("bg-accent animate-pulse rounded-md", className)}
      {...props}
    />
  );
}

export { Skeleton };
