// packages/table-adapter-svelte/demos/spa/ts/src/App.svelte
<script lang="ts">
  import { Router } from "sv-router";
  import { Toaster } from "svelte-sonner";
  import Header from "$lib/components/Header.svelte";
  import "$lib/router";
</script>

<div class="min-h-screen bg-background">
  <Header />
  <main class="container mx-auto px-4 py-6">
    <Router />
  </main>
  <Toaster />
</div>

// packages/sdk/demos/web/spa/vue/ts/src/App.vue
<script setup lang="ts">
import { Toaster } from 'vue-sonner';
import Header from '@/components/Header.vue';
</script>

<template>
  <div class="min-h-screen bg-background">
    <Header />
    <main class="container mx-auto px-4 py-6">
      <router-view />
    </main>
    <Toaster />
  </div>
</template>
