// packages/table-adapter-react/demos/spa/ts/src/pages/CustomerTableInfinite.tsx
import { useDeferredValue, useState, useCallback, useRef, useEffect } from "react";
import { useInfiniteCustomerTable } from "@insurup/table-adapter-react";
import { flexRender } from "@tanstack/react-table";
import { useVirtualizer } from "@tanstack/react-virtual";
import {
  DndContext,
  closestCenter,
  KeyboardSensor,
  PointerSensor,
  useSensor,
  useSensors,
  type DragEndEvent,
} from "@dnd-kit/core";
import {
  arrayMove,
  SortableContext,
  horizontalListSortingStrategy,
} from "@dnd-kit/sortable";
import { useClient } from "@/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Table,
  TableBody,
  TableCell,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { DraggableTableHeader } from "@/components/DraggableTableHeader";
import {
  Search,
  ArrowUpDown,
  ArrowUp,
  ArrowDown,
  RefreshCw,
  Settings2,
  Loader2,
} from "lucide-react";
import { toast } from "sonner";

export function CustomerTableInfinite(): React.ReactElement {
  const client = useClient();
  const [searchInput, setSearchInput] = useState("");
  const deferredSearch = useDeferredValue(searchInput);

  // Container ref for virtualization and scroll detection
  const tableContainerRef = useRef<HTMLDivElement>(null);

  // useInfiniteCustomerTable handles row accumulation automatically!
  // state.rows contains ALL accumulated rows, not just the current page
  const { state, table, adapter } = useInfiniteCustomerTable({
    columns: (col) => [
      col.id({ 
        header: "ID", 
        sortable: true,
        size: 280,
        minSize: 100,
        maxSize: 400,
        enableResizing: true,
        enablePinning: true,
      }),
      col.name({ 
        header: "Name", 
        sortable: true,
        size: 180,
        minSize: 100,
        maxSize: 300,
        enableResizing: true,
      }),
      col.type({ 
        header: "Type", 
        sortable: true,
        size: 120,
        minSize: 80,
        maxSize: 200,
        enableResizing: true,
      }),
      col.primaryEmail({ 
        header: "Email", 
        sortable: true,
        size: 220,
        minSize: 150,
        maxSize: 350,
        enableResizing: true,
      }),
      col.primaryPhoneNumber({ 
        header: "Phone",
        size: 140,
        minSize: 100,
        maxSize: 200,
        enableResizing: true,
      }),
      col.createdAt({ 
        header: "Created", 
        sortable: true,
        sortDescFirst: true,
        size: 120,
        minSize: 100,
        maxSize: 180,
        enableResizing: true,
      }),
    ],
    fetch: (options) => client.customers.getCustomers(options),
    pagination: { type: 'cursor', pageSize: 100 },
    autoFetch: true,
    onError: (error) => {
      toast.error(`Failed to load customers: ${error.message}`);
    },
    tableOptions: {
      columnResizeMode: "onChange",
      enableColumnResizing: true,
      enableSortingRemoval: false,
      initialState: {
        sorting: [{ id: "createdAt", desc: true }],
      },
    },
  });

  // Row virtualizer for efficient rendering
  const rowVirtualizer = useVirtualizer({
    count: state.rows.length,
    getScrollElement: () => tableContainerRef.current,
    estimateSize: () => 48, // estimated row height in px
    overscan: 10, // render 10 extra rows above/below viewport
  });

  // Load more when scrolling near bottom
  const loadMore = useCallback(() => {
    if (table.getCanNextPage() && !state.isFetching) {
      table.nextPage();
    }
  }, [table, state.isFetching]);

  // Scroll event handler for infinite scroll - uses container scroll
  useEffect(() => {
    const container = tableContainerRef.current;
    if (!container) return;

    const handleScroll = () => {
      const { scrollTop, scrollHeight, clientHeight } = container;
      const distanceFromBottom = scrollHeight - scrollTop - clientHeight;
      
      // Load more when within 200px of bottom
      if (distanceFromBottom < 200) {
        loadMore();
      }
    };

    container.addEventListener("scroll", handleScroll, { passive: true });
    
    // Initial check
    handleScroll();
    
    return () => {
      container.removeEventListener("scroll", handleScroll);
    };
  }, [loadMore]);

  // DnD sensors for drag-and-drop column reordering
  const sensors = useSensors(
    useSensor(PointerSensor, {
      activationConstraint: {
        distance: 8,
      },
    }),
    useSensor(KeyboardSensor)
  );

  // Get column IDs for sortable context - read from table state
  const tableColumnOrder = table.getState().columnOrder;
  const columnIds = tableColumnOrder.length > 0 
    ? tableColumnOrder 
    : table.getAllLeafColumns().map((c) => c.id);

  // Handle drag end for column reordering - use table.setColumnOrder directly
  const handleDragEnd = useCallback(
    (event: DragEndEvent) => {
      const { active, over } = event;
      if (over && active.id !== over.id) {
        const currentOrder = table.getState().columnOrder.length > 0
          ? table.getState().columnOrder
          : table.getAllLeafColumns().map((c) => c.id);
        const oldIndex = currentOrder.indexOf(active.id as string);
        const newIndex = currentOrder.indexOf(over.id as string);
        table.setColumnOrder(arrayMove(currentOrder, oldIndex, newIndex));
      }
    },
    [table]
  );

  const handleSearch = useCallback(
    (value: string): void => {
      setSearchInput(value);
      if (value.trim()) {
        adapter.setSearch({
          name: { textSearch: { value: value.trim() } },
        });
      } else {
        adapter.clearSearch();
      }
    },
    [adapter]
  );

  const handleRefresh = useCallback((): void => {
    adapter.invalidate();
    toast.success("Refreshing data...");
  }, [adapter]);

  const getSortIcon = (columnId: string): React.ReactElement => {
    const sorting = table.getState().sorting;
    const sortItem = sorting.find((s) => s.id === columnId);
    if (!sortItem) {
      return <ArrowUpDown className="ml-2 h-4 w-4" />;
    }
    return sortItem.desc ? (
      <ArrowDown className="ml-2 h-4 w-4" />
    ) : (
      <ArrowUp className="ml-2 h-4 w-4" />
    );
  };

  // Check if we've loaded all data
  const hasMoreData = table.getCanNextPage();
  const totalLoaded = state.rows.length;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Customers (Infinite Scroll)</h1>
          <p className="text-muted-foreground">
            Customer table with infinite scroll - scroll down to load more.
          </p>
        </div>
        <Button variant="outline" onClick={handleRefresh} disabled={state.isFetching}>
          <RefreshCw className={`mr-2 h-4 w-4 ${state.isFetching ? "animate-spin" : ""}`} />
          Refresh
        </Button>
      </div>

      <div className="flex items-center gap-4">
        <div className="relative flex-1 max-w-sm">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            placeholder="Search customers..."
            value={searchInput}
            onChange={(e) => handleSearch(e.target.value)}
            className="pl-9"
          />
        </div>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="outline" size="sm">
              <Settings2 className="mr-2 h-4 w-4" />
              Columns
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            {table.getAllColumns()
              .filter((column) => column.getCanHide())
              .map((column) => (
                <DropdownMenuCheckboxItem
                  key={column.id}
                  checked={column.getIsVisible()}
                  onCheckedChange={(value) => column.toggleVisibility(!!value)}
                >
                  {column.id}
                </DropdownMenuCheckboxItem>
              ))}
          </DropdownMenuContent>
        </DropdownMenu>
        <div className="text-sm text-muted-foreground">
          {totalLoaded} customers loaded
        </div>
      </div>

      <DndContext
        sensors={sensors}
        collisionDetection={closestCenter}
        onDragEnd={handleDragEnd}
      >
        {/* Scrollable container with fixed height for virtualization */}
        <div
          ref={tableContainerRef}
          className={`h-[600px] overflow-auto rounded-md border ${searchInput !== deferredSearch ? "opacity-70" : "opacity-100"}`}
        >
          <Table className="w-full table-fixed">
            <TableHeader className="sticky top-0 z-10 bg-background">
              {table.getHeaderGroups().map((headerGroup) => (
                <TableRow key={headerGroup.id}>
                  <SortableContext
                    items={columnIds}
                    strategy={horizontalListSortingStrategy}
                  >
                    {headerGroup.headers.map((header) => (
                      <DraggableTableHeader
                        key={header.id}
                        header={header}
                        onClick={header.column.getCanSort() ? header.column.getToggleSortingHandler() : undefined}
                      >
                        {header.isPlaceholder
                          ? null
                          : flexRender(header.column.columnDef.header, header.getContext())}
                        {header.column.getCanSort() && getSortIcon(header.column.id)}
                      </DraggableTableHeader>
                    ))}
                  </SortableContext>
                </TableRow>
              ))}
            </TableHeader>
            <TableBody>
              {state.isLoading && state.rows.length === 0 ? (
                Array.from({ length: 5 }).map((_, i) => (
                  <TableRow key={`skeleton-${i}`}>
                    {table.getVisibleLeafColumns().map((col) => (
                      <TableCell key={col.id} className="overflow-hidden">
                        <Skeleton className="h-4 w-full" />
                      </TableCell>
                    ))}
                  </TableRow>
                ))
              ) : state.error ? (
                <TableRow>
                  <TableCell
                    colSpan={table.getVisibleLeafColumns().length}
                    className="h-24 text-center text-destructive"
                  >
                    Error: {state.error.message}
                  </TableCell>
                </TableRow>
              ) : state.rows.length === 0 ? (
                <TableRow>
                  <TableCell
                    colSpan={table.getVisibleLeafColumns().length}
                    className="h-24 text-center"
                  >
                    No customers found.
                  </TableCell>
                </TableRow>
              ) : (
                <>
                  {/* Spacer row for virtual scroll offset */}
                  {rowVirtualizer.getVirtualItems().length > 0 && (
                    <tr style={{ height: `${rowVirtualizer.getVirtualItems()[0]?.start ?? 0}px` }} />
                  )}
                  {rowVirtualizer.getVirtualItems().map((virtualRow) => {
                    const row = state.rows[virtualRow.index];
                    const rowData = row as Record<string, unknown>;
                    const rowId = (rowData.id as string) || `row-${virtualRow.index}`;
                    
                    return (
                      <TableRow
                        key={rowId}
                        data-index={virtualRow.index}
                        className="hover:bg-muted/50"
                        style={{ height: `${virtualRow.size}px` }}
                      >
                        {table.getVisibleLeafColumns().map((column) => {
                          const value = rowData[column.id];
                          return (
                            <TableCell key={`${rowId}-${column.id}`} className="overflow-hidden truncate">
                              {column.id === "type" ? (
                                <Badge variant="outline">
                                  {String(value ?? "")}
                                </Badge>
                              ) : column.id === "createdAt" ? (
                                value ? new Date(value as string).toLocaleDateString() : "-"
                              ) : (
                                String(value ?? "-")
                              )}
                            </TableCell>
                          );
                        })}
                      </TableRow>
                    );
                  })}
                  {/* Spacer row for remaining virtual scroll space */}
                  {rowVirtualizer.getVirtualItems().length > 0 && (
                    <tr
                      style={{
                        height: `${rowVirtualizer.getTotalSize() - (rowVirtualizer.getVirtualItems()[rowVirtualizer.getVirtualItems().length - 1]?.end ?? 0)}px`,
                      }}
                    />
                  )}
                </>
              )}
            </TableBody>
          </Table>

          {/* Loading indicator inside scroll container */}
          {state.isFetching && state.rows.length > 0 && (
            <div className="flex items-center justify-center py-4 sticky bottom-0 bg-background/80 backdrop-blur-sm">
              <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
              <span className="ml-2 text-sm text-muted-foreground">Loading more...</span>
            </div>
          )}

          {/* End of data indicator inside scroll container */}
          {!hasMoreData && state.rows.length > 0 && !state.isFetching && (
            <div className="flex items-center justify-center py-4">
              <span className="text-sm text-muted-foreground">
                All {state.rows.length} customers loaded
              </span>
            </div>
          )}
        </div>
      </DndContext>
    </div>
  );
}

// packages/table-adapter-svelte/demos/spa/ts/src/lib/components/CustomerTableInfinite.svelte
<script lang="ts">
  import { onDestroy } from "svelte";
  import { createInfiniteCustomerTable } from "@insurup/table-adapter-svelte";
  import { createVirtualizer } from "@tanstack/svelte-virtual";
  import { getClient } from "$lib/client";
  import { toast } from "svelte-sonner";
  import { dndzone, SHADOW_ITEM_MARKER_PROPERTY_NAME, type DndEvent } from "svelte-dnd-action";
  import {
    Search,
    ArrowUpDown,
    ArrowUp,
    ArrowDown,
    RefreshCw,
    Settings2,
    GripVertical,
    Loader2,
    Pin,
    PinOff,
  } from "@lucide/svelte";

  const client = getClient();
  let searchInput = $state("");
  let showColumnMenu = $state(false);
  let showPinMenu = $state<string | null>(null); // Track which column's pin menu is open
  let pinMenuPosition = $state<{ top: number; left: number } | null>(null); // Position for fixed dropdown
  let containerRef = $state<HTMLDivElement | null>(null);

  // Create infinite customer table instance with resizing enabled
  const ct = createInfiniteCustomerTable(() => ({
    columns: (col) => [
      col.id({ 
        header: "ID", 
        sortable: true,
        size: 280,
        minSize: 100,
        maxSize: 400,
        enableResizing: true,
      }),
      col.name({
        header: "Name",
        sortable: true,
        size: 180,
        minSize: 100,
        maxSize: 300,
        enableResizing: true,
      }),
      col.type({
        header: "Type",
        sortable: true,
        size: 120,
        minSize: 80,
        maxSize: 200,
        enableResizing: true,
      }),
      col.primaryEmail({
        header: "Email",
        sortable: true,
        size: 220,
        minSize: 150,
        maxSize: 350,
        enableResizing: true,
      }),
      col.primaryPhoneNumber({ 
        header: "Phone",
        size: 140,
        minSize: 100,
        maxSize: 200,
        enableResizing: true,
      }),
      col.createdAt({ 
        header: "Created", 
        sortable: true,
        sortDescFirst: true,
        size: 120,
        minSize: 100,
        maxSize: 180,
        enableResizing: true,
      }),
    ],
    fetch: (options) => client.customers.getCustomers(options),
    pagination: { type: 'cursor', pageSize: 100 },
    autoFetch: true,
    onError: (error) => {
      toast.error(`Failed to load customers: ${error.message}`);
    },
    tableOptions: {
      columnResizeMode: "onChange",
      enableColumnResizing: true,
      enableSortingRemoval: false,
      enablePinning: true,
      initialState: {
        sorting: [{ id: "createdAt", desc: true }],
        columnPinning: {
          left: [],
          right: [],
        },
      },
    },
  }));

  onDestroy(() => ct.destroy());

  // Get column info for the dropdown
  const columnInfo = ct.adapter.getColumnInfo();

  // Row virtualizer for efficient rendering
  // Note: createVirtualizer returns a store in svelte-virtual
  let virtualizer = $derived(createVirtualizer<HTMLDivElement, HTMLTableRowElement>({
    count: ct.rows.length,
    getScrollElement: () => containerRef,
    estimateSize: () => 48, // estimated row height in px
    overscan: 10, // render 10 extra rows above/below viewport
  }));

  // Load more when scrolling near bottom
  function loadMore(): void {
    if (ct.table.getCanNextPage() && !ct.isFetching) {
      ct.table.nextPage();
    }
  }

  // Scroll event handler for infinite scroll
  function handleScroll(e: Event): void {
    const container = e.currentTarget as HTMLDivElement;
    if (!container) return;
    
    const { scrollTop, scrollHeight, clientHeight } = container;
    const distanceFromBottom = scrollHeight - scrollTop - clientHeight;
    
    // Load more when within 200px of bottom
    if (distanceFromBottom < 200) {
      loadMore();
    }
  }

  function toggleColumn(columnKey: string): void {
    ct.table.getColumn(columnKey)?.toggleVisibility();
  }

  function handleSearch(value: string): void {
    searchInput = value;
    if (value.trim()) {
      ct.adapter.setSearch({
        name: { textSearch: { value: value.trim() } },
      });
    } else {
      ct.adapter.clearSearch();
    }
  }

  function handleRefresh(): void {
    ct.adapter.invalidate();
    toast.success("Refreshing data...");
  }

  function formatDate(dateStr: unknown): string {
    if (typeof dateStr !== "string") return "-";
    return new Date(dateStr).toLocaleDateString();
  }

  function getSortIcon(columnId: string): "asc" | "desc" | "none" {
    const sorting = ct.table.getState().sorting;
    const sortItem = sorting.find((s) => s.id === columnId);
    if (!sortItem) return "none";
    return sortItem.desc ? "desc" : "asc";
  }

  // DnD column ordering
  interface DndHeaderItem {
    id: string;
    headerId: string;
    [SHADOW_ITEM_MARKER_PROPERTY_NAME]?: boolean;
  }

  // Helper to get unique key for dnd items (shadow items need different keys)
  function getDndItemKey(item: DndHeaderItem): string {
    return item[SHADOW_ITEM_MARKER_PROPERTY_NAME] ? `${item.id}-shadow` : item.id;
  }

  // Get current visible headers for DnD
  function getDndHeaders(): DndHeaderItem[] {
    const headerGroups = ct.table.getHeaderGroups();
    if (headerGroups.length === 0) return [];
    const headers = headerGroups[0].headers;
    return headers.map((h) => ({ id: h.column.id, headerId: h.id }));
  }

  // State for drag-and-drop items
  let dndItems = $state<DndHeaderItem[]>(getDndHeaders());
  let isDragging = $state(false);

  // Track resizing column reactively for proper UI updates
  let resizingColumnId = $derived(ct.table.getState().columnSizingInfo.isResizingColumn);

  // Keep dndItems in sync with table headers (but not during drag)
  $effect(() => {
    if (isDragging) return;
    const newHeaders = getDndHeaders();
    // Only update if the IDs actually changed (not just the reference)
    const currentIds = dndItems
      .filter((i) => !i[SHADOW_ITEM_MARKER_PROPERTY_NAME])
      .map((i) => i.id)
      .join(",");
    const newIds = newHeaders.map((i) => i.id).join(",");
    if (currentIds !== newIds) {
      dndItems = newHeaders;
    }
  });

  function handleDndConsider(e: CustomEvent<DndEvent<DndHeaderItem>>): void {
    isDragging = true;
    dndItems = e.detail.items;
  }

  function handleDndFinalize(e: CustomEvent<DndEvent<DndHeaderItem>>): void {
    isDragging = false;
    // Filter out shadow items when finalizing
    const finalItems = e.detail.items.filter(
      (item) => !item[SHADOW_ITEM_MARKER_PROPERTY_NAME]
    );
    dndItems = finalItems;
    const newOrder = finalItems.map((item) => item.id);
    ct.table.setColumnOrder(newOrder);
  }

  // Get header by column ID
  function getHeader(columnId: string) {
    const headerGroups = ct.table.getHeaderGroups();
    if (headerGroups.length === 0) return null;
    return headerGroups[0].headers.find((h) => h.column.id === columnId) ?? null;
  }

  // Calculate percentage width for a header
  function getPercentWidth(header: ReturnType<typeof getHeader>): number {
    if (!header) return 0;
    const totalSize = ct.table.getTotalSize();
    return (header.getSize() / totalSize) * 100;
  }

  // Column pinning helpers
  function pinColumn(columnId: string, position: "left" | "right" | false): void {
    const column = ct.table.getColumn(columnId);
    if (column) {
      column.pin(position);
    }
    showPinMenu = null;
    pinMenuPosition = null;
  }

  function getColumnPinState(columnId: string): "left" | "right" | false {
    const column = ct.table.getColumn(columnId);
    return column?.getIsPinned() ?? false;
  }

  function openPinMenu(e: MouseEvent, columnId: string): void {
    e.stopPropagation();
    if (showPinMenu === columnId) {
      showPinMenu = null;
      pinMenuPosition = null;
    } else {
      const button = e.currentTarget as HTMLElement;
      const rect = button.getBoundingClientRect();
      pinMenuPosition = {
        top: rect.bottom + 4,
        left: Math.min(rect.right - 128, window.innerWidth - 140), // 128 = dropdown width, ensure it stays on screen
      };
      showPinMenu = columnId;
    }
  }

  // Get sticky position for pinned columns
  function getStickyStyle(header: ReturnType<typeof getHeader>): string {
    if (!header) return "";
    const isPinned = header.column.getIsPinned();
    if (!isPinned) return "";
    
    if (isPinned === "left") {
      const leftOffset = header.column.getStart("left");
      return `position: sticky; left: ${leftOffset}px; z-index: 1;`;
    }
    if (isPinned === "right") {
      const rightOffset = header.column.getAfter("right");
      return `position: sticky; right: ${rightOffset}px; z-index: 1;`;
    }
    return "";
  }

  // Get pinned column class for visual styling
  function getPinnedClass(header: ReturnType<typeof getHeader>): string {
    if (!header) return "";
    const isPinned = header.column.getIsPinned();
    if (!isPinned) return "";
    
    const isLastLeft = header.column.getIsLastColumn("left");
    const isFirstRight = header.column.getIsFirstColumn("right");
    
    let classes = "bg-background";
    if (isLastLeft) classes += " shadow-[2px_0_5px_-2px_rgba(0,0,0,0.1)]";
    if (isFirstRight) classes += " shadow-[-2px_0_5px_-2px_rgba(0,0,0,0.1)]";
    
    return classes;
  }

  // Close pin menu when clicking outside (using document listener for a11y)
  $effect(() => {
    if (!showPinMenu) return;
    
    function handleClickOutside(e: MouseEvent): void {
      const target = e.target as HTMLElement;
      if (!target.closest('[data-pin-menu]')) {
        showPinMenu = null;
        pinMenuPosition = null;
      }
    }

    // Close on scroll to prevent misaligned menu
    function handleScroll(): void {
      showPinMenu = null;
      pinMenuPosition = null;
    }
    
    document.addEventListener('click', handleClickOutside);
    document.addEventListener('scroll', handleScroll, true);
    return () => {
      document.removeEventListener('click', handleClickOutside);
      document.removeEventListener('scroll', handleScroll, true);
    };
  });

  // Check if we've loaded all data
  let hasMoreData = $derived(ct.table.getCanNextPage());
  let totalLoaded = $derived(ct.rows.length);
</script>

<div class="space-y-6">
  <div class="flex items-center justify-between">
    <div>
      <h1 class="text-3xl font-bold tracking-tight">Customers (Infinite Scroll)</h1>
      <p class="text-muted-foreground">
        Customer table with infinite scroll, column pinning, drag-and-drop ordering, and resizing.
      </p>
    </div>
    <button
      class="inline-flex items-center gap-2 h-9 px-4 rounded-md border bg-background hover:bg-accent disabled:opacity-50"
      disabled={ct.isFetching}
      onclick={handleRefresh}
    >
      <RefreshCw class="h-4 w-4 {ct.isFetching ? 'animate-spin' : ''}" />
      Refresh
    </button>
  </div>

  <div class="flex items-center gap-4">
    <div class="relative flex-1 max-w-sm">
      <Search class="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
      <input
        type="text"
        placeholder="Search customers..."
        bind:value={searchInput}
        class="h-9 w-full rounded-md border bg-transparent pl-9 pr-3 text-sm"
        oninput={(e) => handleSearch(e.currentTarget.value)}
      />
    </div>

    <!-- Column visibility dropdown -->
    <div class="relative">
      <button
        class="inline-flex items-center gap-2 h-9 px-4 rounded-md border bg-background hover:bg-accent"
        onclick={() => showColumnMenu = !showColumnMenu}
      >
        <Settings2 class="h-4 w-4" />
        Columns
      </button>
      {#if showColumnMenu}
        <div class="absolute right-0 mt-2 w-48 rounded-md border bg-background shadow-lg z-10">
          <div class="p-2">
            <p class="text-xs font-medium text-muted-foreground mb-2 px-2">Toggle columns</p>
            {#each columnInfo.filter((c) => c.hideable) as col (col.key)}
              <label class="flex items-center gap-2 px-2 py-1.5 rounded hover:bg-accent cursor-pointer">
                <input
                  type="checkbox"
                  checked={ct.table.getState().columnVisibility[col.key] !== false}
                  onchange={() => toggleColumn(col.key)}
                  class="h-4 w-4 rounded border"
                />
                <span class="text-sm">{col.header}</span>
              </label>
            {/each}
          </div>
        </div>
      {/if}
    </div>

    <div class="text-sm text-muted-foreground">
      {totalLoaded} customers loaded
    </div>
  </div>

  <!-- Scrollable container with fixed height for virtualization -->
  <div
    bind:this={containerRef}
    class="h-[600px] overflow-auto rounded-md border"
    onscroll={handleScroll}
  >
    <div style="position: relative; height: {$virtualizer.getTotalSize()}px;">
      <table class="w-full caption-bottom text-sm" style="table-layout: fixed;">
        <thead class="[&_tr]:border-b bg-muted/50 sticky top-0 z-10">
          <tr
            use:dndzone={{
              items: dndItems,
              flipDurationMs: 200,
              type: "columns",
            }}
            onconsider={handleDndConsider}
            onfinalize={handleDndFinalize}
            class="flex w-full"
          >
            {#each dndItems as item (getDndItemKey(item))}
              {@const header = getHeader(item.id)}
              {@const isShadowPlaceholder = !header && item.id.includes('dnd-shadow-placeholder')}
              {@const pinState = getColumnPinState(item.id)}
              {#if header}
                <th
                  class="group relative flex h-10 items-center px-2 text-left align-middle font-medium text-foreground whitespace-nowrap select-none {getPinnedClass(header)}"
                  style="width: {getPercentWidth(header)}%; {getStickyStyle(header)}"
                >
                  <!-- Drag handle (only for unpinned columns) -->
                  {#if !pinState}
                    <button
                      type="button"
                      class="mr-1 cursor-grab touch-none opacity-0 transition-opacity group-hover:opacity-100 active:cursor-grabbing"
                    >
                      <GripVertical class="h-4 w-4 text-muted-foreground" />
                    </button>
                  {/if}

                  <!-- Pin indicator for pinned columns -->
                  {#if pinState}
                    <div class="mr-1 flex items-center">
                      <Pin class="h-3 w-3 text-primary {pinState === 'right' ? 'rotate-90' : '-rotate-90'}" />
                    </div>
                  {/if}

                  <!-- Header content -->
                  {#if header.column.getCanSort()}
                    {@const sortDir = getSortIcon(header.column.id)}
                    <button
                      type="button"
                      class="flex flex-1 items-center overflow-hidden cursor-pointer bg-transparent border-none p-0 text-left font-inherit text-inherit"
                      onclick={header.column.getToggleSortingHandler()}
                    >
                      {#if !header.isPlaceholder}
                        {#if typeof header.column.columnDef.header === "string"}
                          <span class="truncate">{header.column.columnDef.header}</span>
                        {:else}
                          <span class="truncate">{header.column.id}</span>
                        {/if}
                      {/if}
                      {#if sortDir === "desc"}
                        <ArrowDown class="ml-2 h-4 w-4 shrink-0" />
                      {:else if sortDir === "asc"}
                        <ArrowUp class="ml-2 h-4 w-4 shrink-0" />
                      {:else}
                        <ArrowUpDown class="ml-2 h-4 w-4 shrink-0" />
                      {/if}
                    </button>
                  {:else}
                    <span class="flex flex-1 items-center overflow-hidden">
                      {#if !header.isPlaceholder}
                        {#if typeof header.column.columnDef.header === "string"}
                          <span class="truncate">{header.column.columnDef.header}</span>
                        {:else}
                          <span class="truncate">{header.column.id}</span>
                        {/if}
                      {/if}
                    </span>
                  {/if}

                  <!-- Pin menu button -->
                  <div class="relative" data-pin-menu>
                    <button
                      type="button"
                      class="ml-1 p-1 rounded hover:bg-accent opacity-0 group-hover:opacity-100 transition-opacity {showPinMenu === item.id ? 'opacity-100 bg-accent' : ''}"
                      onclick={(e) => openPinMenu(e, item.id)}
                      aria-label="Pin column"
                    >
                      {#if pinState}
                        <PinOff class="h-3 w-3 text-muted-foreground" />
                      {:else}
                        <Pin class="h-3 w-3 text-muted-foreground" />
                      {/if}
                    </button>
                  </div>

                  <!-- Resize handle -->
                  <button
                    type="button"
                    onmousedown={header.getResizeHandler()}
                    ontouchstart={header.getResizeHandler()}
                    ondblclick={() => header.column.resetSize()}
                    class="absolute right-0 top-0 z-10 h-full w-1 cursor-col-resize select-none touch-none bg-border hover:bg-primary border-none p-0 {resizingColumnId === header.column.id ? 'bg-primary' : ''}"
                    aria-label="Resize column"
                  ></button>
                </th>
              {:else if isShadowPlaceholder}
                <!-- Shadow placeholder for drag-and-drop - renders empty space where dragged item will land -->
                <th
                  class="relative flex h-10 items-center px-2 text-left align-middle font-medium text-foreground whitespace-nowrap select-none bg-muted/30"
                  style="flex: 1; min-width: 100px;"
                ></th>
              {/if}
            {/each}
          </tr>
        </thead>
        <tbody class="[&_tr:last-child]:border-0">
          {#if ct.isLoading && ct.rows.length === 0}
            {#each {length: 5} as _}
              <tr class="flex w-full border-b">
                {#each dndItems as item (getDndItemKey(item))}
                  {@const header = getHeader(item.id)}
                  {@const isShadowPlaceholder = !header && item.id.includes('dnd-shadow-placeholder')}
                  {#if header}
                    <td 
                      class="p-2 {getPinnedClass(header)}" 
                      style="width: {getPercentWidth(header)}%; {getStickyStyle(header)}"
                    >
                      <div class="h-4 w-full bg-accent animate-pulse rounded-md"></div>
                    </td>
                  {:else if isShadowPlaceholder}
                    <td class="p-2" style="flex: 1; min-width: 100px;"></td>
                  {/if}
                {/each}
              </tr>
            {/each}
          {:else if ct.isError}
            <tr class="flex w-full">
              <td
                colspan={dndItems.length}
                class="h-24 text-center text-destructive w-full flex items-center justify-center"
              >
                Error: {ct.error?.message}
              </td>
            </tr>
          {:else if ct.isEmpty}
            <tr class="flex w-full">
              <td
                colspan={dndItems.length}
                class="h-24 text-center w-full flex items-center justify-center"
              >
                No customers found.
              </td>
            </tr>
          {:else}
            <!-- Virtualized rows -->
            {#each $virtualizer.getVirtualItems() as virtualRow, idx (virtualRow.index)}
              {@const row = ct.rows[virtualRow.index]}
              {@const rowData = row as Record<string, unknown>}
              <tr
                data-index={virtualRow.index}
                class="flex w-full border-b hover:bg-muted/50"
                style="height: {virtualRow.size}px; transform: translateY({virtualRow.start - idx * virtualRow.size}px);"
              >
                {#each dndItems as item (getDndItemKey(item))}
                  {@const header = getHeader(item.id)}
                  {@const value = rowData[item.id]}
                  {@const isShadowPlaceholder = !header && item.id.includes('dnd-shadow-placeholder')}
                  {#if header}
                    <td 
                      class="p-2 align-middle overflow-hidden truncate flex items-center {getPinnedClass(header)}" 
                      style="width: {getPercentWidth(header)}%; {getStickyStyle(header)}"
                    >
                      {#if item.id === "type"}
                        <span class="inline-flex items-center rounded-full border px-2 py-0.5 text-xs font-medium">
                          {String(value ?? "")}
                        </span>
                      {:else if item.id === "createdAt"}
                        {formatDate(value)}
                      {:else}
                        {String(value ?? "-")}
                      {/if}
                    </td>
                  {:else if isShadowPlaceholder}
                    <td class="p-2 align-middle bg-muted/30" style="flex: 1; min-width: 100px;"></td>
                  {/if}
                {/each}
              </tr>
            {/each}
          {/if}
        </tbody>
      </table>
    </div>

    <!-- Loading indicator inside scroll container -->
    {#if ct.isFetching && ct.hasData}
      <div class="flex items-center justify-center py-4 sticky bottom-0 bg-background/80 backdrop-blur-sm">
        <Loader2 class="h-6 w-6 animate-spin text-muted-foreground" />
        <span class="ml-2 text-sm text-muted-foreground">Loading more...</span>
      </div>
    {/if}

    <!-- End of data indicator inside scroll container -->
    {#if !hasMoreData && ct.hasData && !ct.isFetching}
      <div class="flex items-center justify-center py-4">
        <span class="text-sm text-muted-foreground">
          All {ct.rowCount} customers loaded
        </span>
      </div>
    {/if}
  </div>
</div>

<!-- Pin menu dropdown (rendered with fixed positioning to avoid clipping) -->
{#if showPinMenu && pinMenuPosition}
  {@const columnId = showPinMenu}
  {@const currentPinState = getColumnPinState(columnId)}
  <div 
    class="fixed w-32 rounded-md border bg-background shadow-lg z-50"
    style="top: {pinMenuPosition.top}px; left: {pinMenuPosition.left}px;"
    data-pin-menu
  >
    <div class="p-1">
      {#if currentPinState !== "left"}
        <button
          type="button"
          class="flex w-full items-center gap-2 px-2 py-1.5 text-sm rounded hover:bg-accent text-left"
          onclick={() => pinColumn(columnId, "left")}
        >
          <Pin class="h-3 w-3 -rotate-90" />
          Pin Left
        </button>
      {/if}
      {#if currentPinState !== "right"}
        <button
          type="button"
          class="flex w-full items-center gap-2 px-2 py-1.5 text-sm rounded hover:bg-accent text-left"
          onclick={() => pinColumn(columnId, "right")}
        >
          <Pin class="h-3 w-3 rotate-90" />
          Pin Right
        </button>
      {/if}
      {#if currentPinState}
        <button
          type="button"
          class="flex w-full items-center gap-2 px-2 py-1.5 text-sm rounded hover:bg-accent text-left"
          onclick={() => pinColumn(columnId, false)}
        >
          <PinOff class="h-3 w-3" />
          Unpin
        </button>
      {/if}
    </div>
  </div>
{/if}
