// packages/table-adapter-vue/demos/spa/ts/src/views/Home.vue
<script setup lang="ts">
import { useRouter } from "vue-router";
import { useAuth } from "@/composables/useAuth";
import { TableIcon, Users } from "lucide-vue-next";

const router = useRouter();
const { isAuthenticated, login, loginInProgress } = useAuth();
</script>

<template>
  <div
    v-if="!isAuthenticated"
    class="flex flex-col items-center justify-center min-h-[70vh] text-center"
  >
    <TableIcon class="h-16 w-16 text-primary mb-6" />
    <h1 class="text-4xl font-bold tracking-tight mb-4">
      Table Adapter Vue Demo
    </h1>
    <p class="text-xl text-muted-foreground mb-8 max-w-md">
      A Vue SPA demonstrating the @insurup/table-adapter-vue package
      with TanStack Table integration.
    </p>
    <button
      class="h-10 px-6 rounded-md bg-primary text-primary-foreground hover:bg-primary/90"
      :disabled="loginInProgress"
      @click="login"
    >
      {{ loginInProgress ? "Signing in..." : "Sign in to get started" }}
    </button>
  </div>

  <div
    v-else
    class="space-y-8"
  >
    <div>
      <h1 class="text-3xl font-bold tracking-tight">
        Dashboard
      </h1>
      <p class="text-muted-foreground">
        Welcome to the Table Adapter Vue Demo. Explore the customer table.
      </p>
    </div>

    <div class="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
      <div
        class="cursor-pointer rounded-xl border bg-card p-6 shadow-sm hover:bg-muted/50 transition-colors"
        @click="router.push('/customers')"
      >
        <div class="flex items-center justify-between mb-4">
          <span class="text-sm font-medium">Customer Table</span>
          <Users class="h-4 w-4 text-muted-foreground" />
        </div>
        <p class="text-sm text-muted-foreground">
          View customers using the useCustomerTable composable with TanStack Table.
          Features sorting, pagination, and search.
        </p>
      </div>
    </div>
  </div>
</template>

// packages/table-adapter-svelte/demos/spa/ts/src/lib/components/Home.svelte
<script lang="ts">
  import { Table2, Users } from "@lucide/svelte";
  import { getAuthState, login } from "$lib/auth/index.svelte";
  import { p } from "$lib/router";

  const auth = getAuthState();

  async function handleLogin(): Promise<void> {
    auth.setLoginInProgress(true);
    await login();
  }
</script>

{#if !auth.isAuthenticated}
  <div class="flex flex-col items-center justify-center min-h-[70vh] text-center">
    <Table2 class="h-16 w-16 text-primary mb-6" />
    <h1 class="text-4xl font-bold tracking-tight mb-4">
      Table Adapter Svelte Demo
    </h1>
    <p class="text-xl text-muted-foreground mb-8 max-w-md">
      A Svelte 5 SPA demonstrating the @insurup/table-adapter-svelte package
      with TanStack Table integration.
    </p>
    <button
      class="h-10 px-6 rounded-md bg-primary text-primary-foreground hover:bg-primary/90"
      disabled={auth.loginInProgress}
      onclick={handleLogin}
    >
      {auth.loginInProgress ? "Signing in..." : "Sign in to get started"}
    </button>
  </div>
{:else}
  <div class="space-y-8">
    <div>
      <h1 class="text-3xl font-bold tracking-tight">Dashboard</h1>
      <p class="text-muted-foreground">
        Welcome to the Table Adapter Svelte Demo. Explore the customer table.
      </p>
    </div>

    <div class="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
      <a
        href={p("/customers")}
        class="cursor-pointer rounded-xl border bg-card p-6 shadow-sm hover:bg-muted/50 transition-colors text-left block"
      >
        <div class="flex items-center justify-between mb-4">
          <span class="text-sm font-medium">Customer Table</span>
          <Users class="h-4 w-4 text-muted-foreground" />
        </div>
        <p class="text-sm text-muted-foreground">
          View customers using the createCustomerTable function with TanStack Table.
          Features sorting, pagination, and search.
        </p>
      </a>
    </div>
  </div>
{/if}
