// packages/sdk/demos/web/spa/vue/ts/src/components/ui/TableRow.vue
<script setup lang="ts">
import { cn } from "@/lib/utils";

interface Props {
  class?: string;
}

const props = defineProps<Props>();
</script>

<template>
  <tr :class="cn('border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted', props.class)">
    <slot />
  </tr>
</template>

// packages/sdk/demos/web/spa/svelte/ts/src/lib/components/ui/table-row.svelte
<script lang="ts">
  import { cn } from "$lib/utils";
  import type { HTMLAttributes } from "svelte/elements";

  interface Props extends HTMLAttributes<HTMLTableRowElement> {}

  let { class: className, children, ...restProps }: Props = $props();
</script>

<tr
  class={cn(
    "border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted",
    className
  )}
  {...restProps}
>
  {@render children?.()}
</tr>
