// packages/sdk/demos/web/spa/svelte/ts/src/pages/policies/PolicyList.svelte
<script lang="ts">
  import { navigate } from "$lib/router";
  import { getClient } from "$lib/client";
  import type { QueryPoliciesResultUnifiedFilterInput } from "@insurup/sdk";
  import type { Column } from "$lib/types";
  import DataTable from "$lib/components/DataTable.svelte";
  import Pagination from "$lib/components/Pagination.svelte";
  import { Input, Badge } from "$lib/components/ui";
  import { toast } from "svelte-sonner";
  import { Search } from "lucide-svelte";

  interface Policy {
    id: string;
    policyNumber: string | null;
    productBranch: string | null;
    insuranceCompanyName: string | null;
    customerName: string | null;
    grossPremium: number | null;
    startDate: string | null;
    endDate: string | null;
    state: string | null;
  }

  const sortFieldToApiField: Record<string, string> = {
    policyNumber: "insuranceCompanyPolicyNumber",
  };

  let policies = $state<Policy[]>([]);
  let isLoading = $state(true);
  let totalCount = $state<number | null>(null);
  let pageInfo = $state({
    hasNextPage: false,
    hasPreviousPage: false,
    startCursor: null as string | null,
    endCursor: null as string | null,
  });

  // URL state
  let search = $state("");
  let sortField = $state("startDate");
  let sortDirection = $state<"asc" | "desc">("desc");
  let cursor = $state<string | null>(null);
  let direction = $state("forward");
  let currentPage = $state(1);

  const client = getClient();

  async function fetchPolicies() {
    isLoading = true;
    try {
      const filterOptions: QueryPoliciesResultUnifiedFilterInput | undefined = search
        ? { insuranceCompanyPolicyNumber: { $search: true, textSearch: { value: search } } }
        : undefined;

      const apiSortField = sortFieldToApiField[sortField] || sortField;

      const countPromise = client.policies.getPolicies({
        first: 1,
        filter: filterOptions,
        select: ["id"] as const,
        includeTotalCount: true,
      });

      const result = await client.policies.getPolicies({
        select: [
          "id",
          "insuranceCompanyPolicyNumber",
          "productBranch",
          "insuranceCompanyName",
          "insuredCustomerName",
          "grossPremium",
          "startDate",
          "endDate",
          "state",
        ] as const,
        first: direction === "forward" ? 10 : undefined,
        last: direction === "backward" ? 10 : undefined,
        after: direction === "forward" ? cursor : undefined,
        before: direction === "backward" ? cursor : undefined,
        filter: filterOptions,
        order: apiSortField ? [{ [apiSortField]: sortDirection === "asc" ? "ASC" : "DESC" }] : undefined,
        includeTotalCount: false,
      });

      if (result.isSuccess) {
        const nodes = result.data.nodes?.filter((n): n is NonNullable<typeof n> => n !== null) ?? [];
        policies = nodes.map(n => ({
          id: n.id,
          policyNumber: n.insuranceCompanyPolicyNumber ?? null,
          productBranch: n.productBranch ? String(n.productBranch) : null,
          insuranceCompanyName: n.insuranceCompanyName ?? null,
          customerName: n.insuredCustomerName ?? null,
          grossPremium: n.grossPremium ?? null,
          startDate: n.startDate ? String(n.startDate) : null,
          endDate: n.endDate ? String(n.endDate) : null,
          state: n.state ? String(n.state) : null,
        }));
        pageInfo = {
          hasNextPage: result.data.pageInfo.hasNextPage,
          hasPreviousPage: result.data.pageInfo.hasPreviousPage,
          startCursor: result.data.pageInfo.startCursor ?? null,
          endCursor: result.data.pageInfo.endCursor ?? null,
        };

        countPromise.then((countRes) => {
          if (countRes.isSuccess && countRes.data?.totalCount != null) {
            totalCount = countRes.data.totalCount;
          }
        }).catch(() => {});
      } else {
        toast.error("Failed to load policies");
      }
    } catch (error) {
      toast.error("An error occurred while loading policies");
      console.error(error);
    } finally {
      isLoading = false;
    }
  }

  $effect(() => {
    fetchPolicies();
  });

  function handleSearch(value: string) {
    search = value;
    cursor = null;
    direction = "forward";
    currentPage = 1;
    totalCount = null;
  }

  function handleSort(field: string) {
    if (sortField === field) {
      sortDirection = sortDirection === "asc" ? "desc" : "asc";
    } else {
      sortField = field;
      sortDirection = "asc";
    }
    cursor = null;
    direction = "forward";
    currentPage = 1;
  }

  function handleNextPage() {
    if (pageInfo.endCursor) {
      cursor = pageInfo.endCursor;
      direction = "forward";
      currentPage++;
    }
  }

  function handlePreviousPage() {
    if (pageInfo.startCursor) {
      cursor = pageInfo.startCursor;
      direction = "backward";
      currentPage = Math.max(1, currentPage - 1);
    }
  }

  function formatCurrency(value: number | null): string {
    if (value === null) return "-";
    return new Intl.NumberFormat("tr-TR", {
      style: "currency",
      currency: "TRY",
    }).format(value);
  }

  function formatDate(value: string | null): string {
    if (!value) return "-";
    return new Date(value).toLocaleDateString();
  }

  function getStateVariant(state: string | null): "default" | "secondary" | "destructive" | "outline" {
    switch (state) {
      case "Active":
      case "ACTIVE":
        return "default";
      case "Expired":
      case "EXPIRED":
        return "secondary";
      case "Cancelled":
      case "CANCELLED":
        return "destructive";
      default:
        return "outline";
    }
  }

  const columns: Column<Policy>[] = [
    {
      key: "policyNumber",
      header: "Policy Number",
      sortable: true,
      render: (policy) => policy.policyNumber || "-",
    },
    {
      key: "productBranch",
      header: "Branch",
    },
    {
      key: "insuranceCompanyName",
      header: "Insurance Company",
      render: (policy) => policy.insuranceCompanyName || "-",
    },
    {
      key: "customerName",
      header: "Customer",
      render: (policy) => policy.customerName || "-",
    },
    {
      key: "grossPremium",
      header: "Premium",
      sortable: true,
      render: (policy) => formatCurrency(policy.grossPremium),
    },
    {
      key: "startDate",
      header: "Start Date",
      sortable: true,
      render: (policy) => formatDate(policy.startDate),
    },
    {
      key: "endDate",
      header: "End Date",
      render: (policy) => formatDate(policy.endDate),
    },
    {
      key: "state",
      header: "Status",
    },
  ];
</script>

<div class="space-y-6">
  <div>
    <h1 class="text-3xl font-bold tracking-tight">Policies</h1>
    <p class="text-muted-foreground">
      Browse and manage insurance policies.
    </p>
  </div>

  <div class="flex items-center gap-4">
    <div class="relative flex-1 max-w-sm">
      <Search class="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
      <Input
        placeholder="Search policies..."
        value={search}
        oninput={(e) => handleSearch(e.currentTarget.value)}
        class="pl-9"
      />
    </div>
  </div>

  <DataTable
    {columns}
    data={policies}
    {isLoading}
    {sortField}
    {sortDirection}
    onSort={handleSort}
    onRowClick={(policy) => navigate("/policies/:id", { params: { id: policy.id } })}
    getRowKey={(policy) => policy.id}
  >
    {#snippet renderCell({ item, column })}
      {#if column.key === "productBranch"}
        <Badge variant="outline">{item.productBranch || "-"}</Badge>
      {:else if column.key === "state"}
        <Badge variant={getStateVariant(item.state)}>
          {item.state || "-"}
        </Badge>
      {:else if column.render}
        {column.render(item)}
      {:else}
        {String((item as unknown as Record<string, unknown>)[column.key] ?? "")}
      {/if}
    {/snippet}
  </DataTable>

  <Pagination
    hasNextPage={pageInfo.hasNextPage}
    hasPreviousPage={pageInfo.hasPreviousPage}
    onNext={handleNextPage}
    onPrevious={handlePreviousPage}
    {isLoading}
    {totalCount}
    {currentPage}
    pageSize={10}
  />
</div>

// packages/sdk/demos/web/spa/react/ts/src/pages/policies/PolicyList.tsx
import { useState, useEffect, useDeferredValue, useCallback } from 'react';
import { useNavigate } from 'react-router';
import { useQueryState, parseAsString, parseAsInteger, parseAsStringLiteral } from 'nuqs';
import type { QueryPoliciesResultUnifiedFilterInput } from '@insurup/sdk';
import { useClient } from '@/client';
import { DataTable, type Column } from '@/components/DataTable';
import { Pagination } from '@/components/Pagination';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { toast } from 'sonner';
import { Search } from 'lucide-react';

interface Policy {
  id: string;
  policyNumber: string | null;
  productBranch: string | null;
  insuranceCompanyName: string | null;
  customerName: string | null;
  grossPremium: number | null;
  startDate: string | null;
  endDate: string | null;
  state: string | null;
}

// Map UI column keys to API field names
const sortFieldToApiField: Record<string, string> = {
  policyNumber: 'insuranceCompanyPolicyNumber',
};

export function PolicyList() {
  const client = useClient();
  const navigate = useNavigate();

  const [policies, setPolicies] = useState<Policy[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [totalCount, setTotalCount] = useState<number | null>(null);
  const [pageInfo, setPageInfo] = useState<{
    hasNextPage: boolean;
    hasPreviousPage: boolean;
    startCursor?: string | null;
    endCursor?: string | null;
  }>({ hasNextPage: false, hasPreviousPage: false });

  // URL state with nuqs
  const [search, setSearch] = useQueryState('search', parseAsString.withDefault(''));
  const [sortField, setSortField] = useQueryState('sort', parseAsString.withDefault('startDate'));
  const [sortDirection, setSortDirection] = useQueryState(
    'dir',
    parseAsStringLiteral(['asc', 'desc'] as const).withDefault('desc')
  );
  const [cursor, setCursor] = useQueryState('cursor', parseAsString);
  const [direction, setDirection] = useQueryState(
    'direction',
    parseAsString.withDefault('forward')
  );
  const [currentPage, setCurrentPage] = useQueryState('page', parseAsInteger.withDefault(1));

  const deferredSearch = useDeferredValue(search);

  const fetchPolicies = useCallback(async () => {
    setIsLoading(true);
    try {
      const filterOptions: QueryPoliciesResultUnifiedFilterInput | undefined = deferredSearch
        ? {
            insuranceCompanyPolicyNumber: {
              $search: true,
              textSearch: deferredSearch,
            },
          }
        : undefined;

      // Map UI sort field to API field name
      const apiSortField = sortFieldToApiField[sortField] || sortField;

      // Fire count query in parallel (non-blocking)
      const countPromise = client.policies.getPolicies({
        first: 1,
        filter: filterOptions,
        select: ['id'] as const,
        includeTotalCount: true,
      });

      // Await only the main data query
      const result = await client.policies.getPolicies({
        select: [
          'id',
          'insuranceCompanyPolicyNumber',
          'productBranch',
          'insuranceCompanyName',
          'insuredCustomerName',
          'grossPremium',
          'startDate',
          'endDate',
          'state',
        ] as const,
        first: direction === 'forward' ? 10 : undefined,
        last: direction === 'backward' ? 10 : undefined,
        after: direction === 'forward' ? cursor : undefined,
        before: direction === 'backward' ? cursor : undefined,
        filter: filterOptions,
        order: apiSortField
          ? [{ [apiSortField]: sortDirection === 'asc' ? 'ASC' : 'DESC' }]
          : undefined,
        includeTotalCount: false,
      });

      if (result.isSuccess) {
        const nodes =
          result.data.nodes?.filter((n): n is NonNullable<typeof n> => n !== null) ?? [];
        setPolicies(
          nodes.map((n) => ({
            id: n.id,
            policyNumber: n.insuranceCompanyPolicyNumber ?? null,
            productBranch: n.productBranch ? String(n.productBranch) : null,
            insuranceCompanyName: n.insuranceCompanyName ?? null,
            customerName: n.insuredCustomerName ?? null,
            grossPremium: n.grossPremium ?? null,
            startDate: n.startDate ? String(n.startDate) : null,
            endDate: n.endDate ? String(n.endDate) : null,
            state: n.state ? String(n.state) : null,
          }))
        );
        setPageInfo(result.data.pageInfo);

        // Update count when it resolves (non-blocking)
        countPromise
          .then((countRes) => {
            if (countRes.isSuccess && countRes.data?.totalCount != null) {
              setTotalCount(countRes.data.totalCount);
            }
          })
          .catch(() => {
            // Silently ignore count errors - not critical
          });
      } else {
        toast.error('Failed to load policies');
      }
    } catch (error) {
      toast.error('An error occurred while loading policies');
      console.error(error);
    } finally {
      setIsLoading(false);
    }
  }, [client.policies, cursor, deferredSearch, direction, sortDirection, sortField]);

  useEffect(() => {
    fetchPolicies();
  }, [fetchPolicies]);

  const handleSearch = (value: string) => {
    setSearch(value || null);
    // Reset pagination when searching
    setCursor(null);
    setDirection(null);
    setCurrentPage(1);
    setTotalCount(null);
  };

  const handleSort = (field: string) => {
    if (sortField === field) {
      setSortDirection(sortDirection === 'asc' ? 'desc' : 'asc');
    } else {
      setSortField(field);
      setSortDirection('asc');
    }
    // Reset pagination when sorting
    setCursor(null);
    setDirection(null);
    setCurrentPage(1);
  };

  const handleNextPage = () => {
    if (pageInfo.endCursor) {
      setCursor(pageInfo.endCursor);
      setDirection('forward');
      setCurrentPage((p) => (p ?? 1) + 1);
    }
  };

  const handlePreviousPage = () => {
    if (pageInfo.startCursor) {
      setCursor(pageInfo.startCursor);
      setDirection('backward');
      setCurrentPage((p) => Math.max(1, (p ?? 1) - 1));
    }
  };

  const formatCurrency = (value: number | null) => {
    if (value === null) return '-';
    return new Intl.NumberFormat('tr-TR', {
      style: 'currency',
      currency: 'TRY',
    }).format(value);
  };

  const formatDate = (value: string | null) => {
    if (!value) return '-';
    return new Date(value).toLocaleDateString();
  };

  const getStateVariant = (state: string | null) => {
    switch (state) {
      case 'Active':
      case 'ACTIVE':
        return 'default';
      case 'Expired':
      case 'EXPIRED':
        return 'secondary';
      case 'Cancelled':
      case 'CANCELLED':
        return 'destructive';
      default:
        return 'outline';
    }
  };

  const columns: Column<Policy>[] = [
    {
      key: 'policyNumber',
      header: 'Policy Number',
      sortable: true,
      render: (policy) => policy.policyNumber || '-',
    },
    {
      key: 'productBranch',
      header: 'Branch',
      render: (policy) => <Badge variant="outline">{policy.productBranch || '-'}</Badge>,
    },
    {
      key: 'insuranceCompanyName',
      header: 'Insurance Company',
      render: (policy) => policy.insuranceCompanyName || '-',
    },
    {
      key: 'customerName',
      header: 'Customer',
      render: (policy) => policy.customerName || '-',
    },
    {
      key: 'grossPremium',
      header: 'Premium',
      sortable: true,
      render: (policy) => formatCurrency(policy.grossPremium),
    },
    {
      key: 'startDate',
      header: 'Start Date',
      sortable: true,
      render: (policy) => formatDate(policy.startDate),
    },
    {
      key: 'endDate',
      header: 'End Date',
      render: (policy) => formatDate(policy.endDate),
    },
    {
      key: 'state',
      header: 'Status',
      render: (policy) => (
        <Badge variant={getStateVariant(policy.state)}>{policy.state || '-'}</Badge>
      ),
    },
  ];

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Policies</h1>
        <p className="text-muted-foreground">Browse and manage insurance policies.</p>
      </div>

      <div className="flex items-center gap-4">
        <div className="relative flex-1 max-w-sm">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            placeholder="Search policies..."
            value={search}
            onChange={(e) => handleSearch(e.target.value)}
            className="pl-9"
          />
        </div>
      </div>

      <div style={{ opacity: search !== deferredSearch ? 0.7 : 1 }}>
        <DataTable
          columns={columns}
          data={policies}
          isLoading={isLoading}
          sortField={sortField}
          sortDirection={sortDirection}
          onSort={handleSort}
          onRowClick={(policy) => navigate(`/policies/${policy.id}`)}
          getRowKey={(policy) => policy.id}
        />
      </div>

      <Pagination
        hasNextPage={pageInfo.hasNextPage}
        hasPreviousPage={pageInfo.hasPreviousPage}
        onNext={handleNextPage}
        onPrevious={handlePreviousPage}
        isLoading={isLoading}
        totalCount={totalCount}
        currentPage={currentPage}
        pageSize={10}
      />
    </div>
  );
}
