// packages/sdk/demos/web/spa/angular/ts/src/app/components/customer-create-dialog.component.ts
import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { ClientService } from '../services/client.service';
import { CustomerType } from '@insurup/contracts';

@Component({
  selector: 'app-customer-create-dialog',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatDialogModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatSnackBarModule,
  ],
  template: `
    <h2 mat-dialog-title>Create Customer</h2>
    <mat-dialog-content>
      <p class="dialog-description">Add a new individual customer to the system.</p>
      
      <form class="form-container">
        <mat-form-field appearance="outline" class="full-width">
          <mat-label>Full Name *</mat-label>
          <input matInput [(ngModel)]="fullName" name="fullName" required>
        </mat-form-field>

        <mat-form-field appearance="outline" class="full-width">
          <mat-label>Identity Number (TC Kimlik No)</mat-label>
          <input matInput [(ngModel)]="identityNumber" name="identityNumber" maxlength="11">
        </mat-form-field>

        <mat-form-field appearance="outline" class="full-width">
          <mat-label>Birth Date</mat-label>
          <input matInput type="date" [(ngModel)]="birthDate" name="birthDate">
        </mat-form-field>

        <mat-form-field appearance="outline" class="full-width">
          <mat-label>Email Address</mat-label>
          <input matInput type="email" [(ngModel)]="email" name="email">
        </mat-form-field>

        <mat-form-field appearance="outline" class="full-width">
          <mat-label>Phone Number</mat-label>
          <input matInput [(ngModel)]="phoneNumber" name="phoneNumber" maxlength="10">
          <mat-hint>Enter 10-digit phone number without country code</mat-hint>
        </mat-form-field>

        @if (error()) {
          <p class="error-message">{{ error() }}</p>
        }
      </form>
    </mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button mat-dialog-close [disabled]="isPending()">Cancel</button>
      <button mat-raised-button color="primary" 
              (click)="submit()" 
              [disabled]="isPending() || !fullName">
        {{ isPending() ? 'Creating...' : 'Create Customer' }}
      </button>
    </mat-dialog-actions>
  `,
  styles: [`
    .dialog-description {
      margin-bottom: 16px;
      opacity: 0.7;
    }
    .form-container {
      display: flex;
      flex-direction: column;
      gap: 8px;
      min-width: 400px;
    }
    .full-width {
      width: 100%;
    }
    .error-message {
      color: var(--mat-warn-color);
    }
  `],
})
export class CustomerCreateDialogComponent {
  private dialogRef = inject(MatDialogRef<CustomerCreateDialogComponent>);
  private clientService = inject(ClientService);
  private router = inject(Router);
  private snackBar = inject(MatSnackBar);

  fullName = '';
  identityNumber = '';
  birthDate = '';
  email = '';
  phoneNumber = '';

  isPending = signal(false);
  error = signal<string | null>(null);

  async submit(): Promise<void> {
    this.isPending.set(true);
    this.error.set(null);

    try {
      const result = await this.clientService.customers.createCustomer({
        type: CustomerType.Individual,
        fullName: this.fullName,
        email: this.email || undefined,
        phoneNumber: this.phoneNumber
          ? { countryCode: 90, number: this.phoneNumber }
          : undefined,
        identityNumber: this.identityNumber || '',
        birthDate: this.birthDate || undefined,
        fillMissingFields: false,
      });

      if (result.isSuccess) {
        this.snackBar.open('Customer created successfully', 'Close', { duration: 3000 });
        this.dialogRef.close(true);
        this.router.navigate(['/customers', result.data.id]);
      } else {
        this.error.set('Failed to create customer');
        this.snackBar.open('Failed to create customer', 'Close', { duration: 3000 });
      }
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'An error occurred';
      this.error.set(errorMessage);
      this.snackBar.open(errorMessage, 'Close', { duration: 3000 });
    } finally {
      this.isPending.set(false);
    }
  }
}

// packages/sdk/demos/web/spa/svelte/ts/src/lib/components/CustomerCreateDialog.svelte
<script lang="ts">
  import { navigate } from "$lib/router";
  import { getClient } from "$lib/client";
  import {
    Button,
    Input,
    Label,
    Dialog,
    DialogContent,
    DialogHeader,
    DialogFooter,
    DialogTitle,
    DialogDescription,
  } from "$lib/components/ui";
  import { toast } from "svelte-sonner";
  import { CustomerType } from "@insurup/contracts";

  interface Props {
    open: boolean;
    onOpenChange: (open: boolean) => void;
  }

  let { open = $bindable(), onOpenChange }: Props = $props();

  let isPending = $state(false);
  let error = $state<string | null>(null);

  // Form fields
  let fullName = $state("");
  let identityNumber = $state("");
  let birthDate = $state("");
  let email = $state("");
  let phoneNumber = $state("");

  async function handleSubmit(e: Event) {
    e.preventDefault();
    isPending = true;
    error = null;

    try {
      const client = getClient();
      const result = await client.customers.createCustomer({
        type: CustomerType.Individual,
        fullName,
        email: email || undefined,
        phoneNumber: phoneNumber
          ? { countryCode: 90, number: phoneNumber }
          : undefined,
        identityNumber: identityNumber || "",
        birthDate: birthDate || undefined,
        fillMissingFields: false,
      });

      if (result.isSuccess) {
        toast.success("Customer created successfully");
        onOpenChange(false);
        resetForm();
        navigate("/customers/:id", { params: { id: result.data.id } });
      } else {
        toast.error("Failed to create customer");
        error = "Failed to create customer";
      }
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : "An error occurred";
      toast.error(errorMessage);
      error = errorMessage;
    } finally {
      isPending = false;
    }
  }

  function resetForm() {
    fullName = "";
    identityNumber = "";
    birthDate = "";
    email = "";
    phoneNumber = "";
    error = null;
  }

  function handleClose(newOpen: boolean) {
    if (!newOpen) {
      resetForm();
    }
    onOpenChange(newOpen);
  }
</script>

<Dialog bind:open onOpenChange={handleClose}>
  <DialogContent class="sm:max-w-[425px]">
    <DialogHeader>
      <DialogTitle>Create Customer</DialogTitle>
      <DialogDescription>
        Add a new individual customer to the system.
      </DialogDescription>
    </DialogHeader>
    <form onsubmit={handleSubmit} class="space-y-4">
      <div class="space-y-2">
        <Label for="fullName">
          Full Name <span class="text-destructive">*</span>
        </Label>
        <Input
          id="fullName"
          name="fullName"
          placeholder="Enter full name"
          required
          bind:value={fullName}
        />
      </div>

      <div class="space-y-2">
        <Label for="identityNumber">
          Identity Number (TC Kimlik No)
        </Label>
        <Input
          id="identityNumber"
          name="identityNumber"
          placeholder="11-digit identity number"
          maxlength={11}
          pattern="[0-9]{11}"
          bind:value={identityNumber}
        />
      </div>

      <div class="space-y-2">
        <Label for="birthDate">Birth Date</Label>
        <Input id="birthDate" name="birthDate" type="date" bind:value={birthDate} />
      </div>

      <div class="space-y-2">
        <Label for="email">Email Address</Label>
        <Input
          id="email"
          name="email"
          type="email"
          placeholder="customer@example.com"
          bind:value={email}
        />
      </div>

      <div class="space-y-2">
        <Label for="phoneNumber">Phone Number</Label>
        <Input
          id="phoneNumber"
          name="phoneNumber"
          placeholder="5XX XXX XX XX"
          maxlength={10}
          pattern="[0-9]{10}"
          bind:value={phoneNumber}
        />
        <p class="text-xs text-muted-foreground">
          Enter 10-digit phone number without country code
        </p>
      </div>

      {#if error}
        <div class="text-sm text-destructive">{error}</div>
      {/if}

      <DialogFooter class="gap-2 pt-4">
        <Button
          type="button"
          variant="outline"
          onclick={() => handleClose(false)}
          disabled={isPending}
        >
          Cancel
        </Button>
        <Button type="submit" disabled={isPending}>
          {isPending ? "Creating..." : "Create Customer"}
        </Button>
      </DialogFooter>
    </form>
  </DialogContent>
</Dialog>
